
# SwiftLint Configuration File

disabled_rules: # rules to disable
  - trailing_whitespace
  - force_cast
  - force_try
  - line_length

opt_in_rules: # some rules are only opt-in
  - empty_count
  - explicit_init
  - fatal_error_message

included: 
  - Sources
  - Tests

excluded:
  - Carthage
  - Pods
  - .build
  - Generated

# Customize rules
line_length:
  warning: 120
  error: 200

type_name:
  min_length:
    warning: 3
  max_length:
    warning: 40

identifier_name:
  min_length: 
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 60

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 300
  error: 500
